import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import Header from '../components/header'
import Footer from '../components/footer'

const Home: NextPage = ({ areas }) => {
    return (
        <div className="">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="">
                <div>
                    <h1 className='text-3xl font-bold underline'>AREAS 一覧</h1>

                    {areas.map((area => {
                        return (
                            <ul className='mt-4'>
                                {Object.keys(area).map(key => {
                                    // data.push(area[key]);
                                    return (
                                        <li>{key}:{area[key]}</li>
                                    )
                                })}
                            </ul>
                        )
                    }))}
                </div>
            </div>

        </div>
    )
}

export default Home

export async function getServerSideProps() {
    const res = await fetch(`http://nginx:80/api/areas`)
    const areas = await res.json()

    if (!areas) {
        return {
            notFound: true,
        }
    }
    return {
        props: { areas }, // will be passed to the page component as props
    }
}